name: "Committed Node"
description: "Build with Node"

inputs:
  apt:
    description: "apt packages to get"
    required: false
    default: ""
  build:
    description: "Run build"
    required: false
    default: "true"
  test:
    description: "Runs test"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - id: apt-install
      name: apt install
      shell: bash
      run: '[[ -z "$INPUT_APT" ]] && apt-get update && apt-get install -y --no-recommends ${INPUT_APT}'
    - id: node-install
      name: Install via npm
      shell: bash
      run: |
        npm ci
    - id: node-format-check
      shell: bash
      run: npm run format:check --if-present
    - id: node-build
      name: Build
      shell: bash
      run: '[[ "$INPUT_BUILD" == "true" ]] && npm run build --if-present'
    - id: node-test
      name: Test
      shell: bash
      run: '[[ "$INPUT_TEST" == "true" ]] && npm test'
    - id: node-lint-check
      name: Check linting
      shell: bash
      run: node run lint:check --if-present
    - id: node-sonar
      shell: bash
      run: npm run sonar --if-present
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR: ${{ github.event.number }}
